# Generated by Django 5.1.5 on 2025-02-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImageReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applung.patient')),
            ],
        ),
    ]
